name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t demo-secure-app ./docker

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo-secure-app

      - name: Install Checkov
        run: pip install checkov

      - name: Scan Terraform code
        run: checkov -d terraform
